// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/storage_service.proto

package org.ebook_searching.storage_service;

public final class StorageServiceOuterClass {
  private StorageServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfirmFileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.ebook_searching.storage_service.ConfirmFileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The path of the file to confirm
     * </pre>
     *
     * <code>string filePath = 1;</code>
     * @return The filePath.
     */
    java.lang.String getFilePath();
    /**
     * <pre>
     * The path of the file to confirm
     * </pre>
     *
     * <code>string filePath = 1;</code>
     * @return The bytes for filePath.
     */
    com.google.protobuf.ByteString
        getFilePathBytes();
  }
  /**
   * <pre>
   * Request message for confirming a file
   * </pre>
   *
   * Protobuf type {@code org.ebook_searching.storage_service.ConfirmFileRequest}
   */
  public static final class ConfirmFileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.ebook_searching.storage_service.ConfirmFileRequest)
      ConfirmFileRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfirmFileRequest.newBuilder() to construct.
    private ConfirmFileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfirmFileRequest() {
      filePath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfirmFileRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfirmFileRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filePath_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest.class, org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest.Builder.class);
    }

    public static final int FILEPATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object filePath_;
    /**
     * <pre>
     * The path of the file to confirm
     * </pre>
     *
     * <code>string filePath = 1;</code>
     * @return The filePath.
     */
    @java.lang.Override
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The path of the file to confirm
     * </pre>
     *
     * <code>string filePath = 1;</code>
     * @return The bytes for filePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filePath_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filePath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest)) {
        return super.equals(obj);
      }
      org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest other = (org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest) obj;

      if (!getFilePath()
          .equals(other.getFilePath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request message for confirming a file
     * </pre>
     *
     * Protobuf type {@code org.ebook_searching.storage_service.ConfirmFileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.ebook_searching.storage_service.ConfirmFileRequest)
        org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest.class, org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest.Builder.class);
      }

      // Construct using org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        filePath_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_descriptor;
      }

      @java.lang.Override
      public org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest getDefaultInstanceForType() {
        return org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest build() {
        org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest buildPartial() {
        org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest result = new org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest(this);
        result.filePath_ = filePath_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest) {
          return mergeFrom((org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest other) {
        if (other == org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest.getDefaultInstance()) return this;
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object filePath_ = "";
      /**
       * <pre>
       * The path of the file to confirm
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @return The filePath.
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The path of the file to confirm
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @return The bytes for filePath.
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The path of the file to confirm
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @param value The filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The path of the file to confirm
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilePath() {
        
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The path of the file to confirm
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @param value The bytes for filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filePath_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.ebook_searching.storage_service.ConfirmFileRequest)
    }

    // @@protoc_insertion_point(class_scope:org.ebook_searching.storage_service.ConfirmFileRequest)
    private static final org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest();
    }

    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfirmFileRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConfirmFileRequest>() {
      @java.lang.Override
      public ConfirmFileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfirmFileRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfirmFileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfirmFileRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfirmFileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.ebook_searching.storage_service.ConfirmFileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The confirmed file path
     * </pre>
     *
     * <code>string filePath = 1;</code>
     * @return The filePath.
     */
    java.lang.String getFilePath();
    /**
     * <pre>
     * The confirmed file path
     * </pre>
     *
     * <code>string filePath = 1;</code>
     * @return The bytes for filePath.
     */
    com.google.protobuf.ByteString
        getFilePathBytes();

    /**
     * <pre>
     * Whether the confirmation was successful
     * </pre>
     *
     * <code>bool success = 2;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <pre>
     * Optional message (e.g., error or success details)
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Optional message (e.g., error or success details)
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * Response message for confirming a file
   * </pre>
   *
   * Protobuf type {@code org.ebook_searching.storage_service.ConfirmFileResponse}
   */
  public static final class ConfirmFileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.ebook_searching.storage_service.ConfirmFileResponse)
      ConfirmFileResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfirmFileResponse.newBuilder() to construct.
    private ConfirmFileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfirmFileResponse() {
      filePath_ = "";
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfirmFileResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfirmFileResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filePath_ = s;
              break;
            }
            case 16: {

              success_ = input.readBool();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse.class, org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse.Builder.class);
    }

    public static final int FILEPATH_FIELD_NUMBER = 1;
    private volatile java.lang.Object filePath_;
    /**
     * <pre>
     * The confirmed file path
     * </pre>
     *
     * <code>string filePath = 1;</code>
     * @return The filePath.
     */
    @java.lang.Override
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The confirmed file path
     * </pre>
     *
     * <code>string filePath = 1;</code>
     * @return The bytes for filePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <pre>
     * Whether the confirmation was successful
     * </pre>
     *
     * <code>bool success = 2;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Optional message (e.g., error or success details)
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Optional message (e.g., error or success details)
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filePath_);
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filePath_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse)) {
        return super.equals(obj);
      }
      org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse other = (org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse) obj;

      if (!getFilePath()
          .equals(other.getFilePath())) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILEPATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response message for confirming a file
     * </pre>
     *
     * Protobuf type {@code org.ebook_searching.storage_service.ConfirmFileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.ebook_searching.storage_service.ConfirmFileResponse)
        org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse.class, org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse.Builder.class);
      }

      // Construct using org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        filePath_ = "";

        success_ = false;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ebook_searching.storage_service.StorageServiceOuterClass.internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_descriptor;
      }

      @java.lang.Override
      public org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse getDefaultInstanceForType() {
        return org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse build() {
        org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse buildPartial() {
        org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse result = new org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse(this);
        result.filePath_ = filePath_;
        result.success_ = success_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse) {
          return mergeFrom((org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse other) {
        if (other == org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse.getDefaultInstance()) return this;
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          onChanged();
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object filePath_ = "";
      /**
       * <pre>
       * The confirmed file path
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @return The filePath.
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The confirmed file path
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @return The bytes for filePath.
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The confirmed file path
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @param value The filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The confirmed file path
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilePath() {
        
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The confirmed file path
       * </pre>
       *
       * <code>string filePath = 1;</code>
       * @param value The bytes for filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filePath_ = value;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <pre>
       * Whether the confirmation was successful
       * </pre>
       *
       * <code>bool success = 2;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * Whether the confirmation was successful
       * </pre>
       *
       * <code>bool success = 2;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether the confirmation was successful
       * </pre>
       *
       * <code>bool success = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Optional message (e.g., error or success details)
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Optional message (e.g., error or success details)
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Optional message (e.g., error or success details)
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional message (e.g., error or success details)
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional message (e.g., error or success details)
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.ebook_searching.storage_service.ConfirmFileResponse)
    }

    // @@protoc_insertion_point(class_scope:org.ebook_searching.storage_service.ConfirmFileResponse)
    private static final org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse();
    }

    public static org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfirmFileResponse>
        PARSER = new com.google.protobuf.AbstractParser<ConfirmFileResponse>() {
      @java.lang.Override
      public ConfirmFileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfirmFileResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfirmFileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfirmFileResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ebook_searching.storage_service.StorageServiceOuterClass.ConfirmFileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032grpc/storage_service.proto\022#org.ebook_" +
      "searching.storage_service\"&\n\022ConfirmFile" +
      "Request\022\020\n\010filePath\030\001 \001(\t\"I\n\023ConfirmFile" +
      "Response\022\020\n\010filePath\030\001 \001(\t\022\017\n\007success\030\002 " +
      "\001(\010\022\017\n\007message\030\003 \001(\t2\230\001\n\016StorageService\022" +
      "\205\001\n\020ConfirmFileUsage\0227.org.ebook_searchi" +
      "ng.storage_service.ConfirmFileRequest\0328." +
      "org.ebook_searching.storage_service.Conf" +
      "irmFileResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_ebook_searching_storage_service_ConfirmFileRequest_descriptor,
        new java.lang.String[] { "FilePath", });
    internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_ebook_searching_storage_service_ConfirmFileResponse_descriptor,
        new java.lang.String[] { "FilePath", "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
