spring:
  cloud:
    gateway:
      routes:
        # Route for Admin Management Service
        - id: admin-service
          uri: http://${ADMIN_SERVICE_HOST:localhost}:8082  # Assuming the Admin Management Service runs on port 8081
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/admin/(?<segment>.*), /api/${segment}

        # Route for Book Service
        - id: book-service
          uri: http://${BOOK_SERVICE_HOST:localhost}:8083
          predicates:
            - Path=/api/books/**
          filters:
            - RewritePath=/api/books/(?<segment>.*), /api/${segment}

        # Route for Ontology Service
        - id: ontology-service
          uri: http://${ONTOLOGY_SERVICE_HOST:localhost}:8084
          predicates:
            - Path=/api/ontology/**
          filters:
            - RewritePath=/api/ontology/(?<segment>.*), /api/${segment}
        # Route for Ontology Service
        - id: auth-service
          uri: http://${AUTH_SERVICE_HOST:localhost}:8085
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/${segment}
  server:
    port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: admin-service
        url: /api/admin/v3/api-docs
      - name: ontology-service
        url: /api/ontology/v3/api-docs
      - name: book-service
        url: /api/books/v3/api-docs
      - name: auth-service
        url: /api/auth/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
