openapi: 3.1.0
info:
  title: eBook Searching App API
  description: API for managing and searching eBooks, users, and their preferences.
  version: 1.0.0
servers:
  - url: https://api.ebooksearchingapp.com/v1
    description: Production server
  - url: https://staging.api.ebooksearchingapp.com/v1
    description: Staging server

paths:
  /ebooks/search:
    get:
      summary: Search for eBooks
      description: Retrieve a list of eBooks based on search criteria like title, author, category, and language.
      parameters:
        - name: query
          in: query
          description: Keywords for searching (e.g., title or author name)
          required: true
          schema:
            type: string
        - name: category
          in: query
          description: Filter by category
          required: false
          schema:
            type: string
        - name: language
          in: query
          description: Filter by language
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: Number of results per page
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: A list of eBooks matching the search criteria
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalResults:
                    type: integer
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Book'
        '400':
          description: Invalid request parameters

  /ebooks/{id}:
    get:
      summary: Get eBook Details
      description: Retrieve detailed information about a specific eBook.
      parameters:
        - name: id
          in: path
          description: ID of the eBook
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the eBook
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: eBook not found

  /users/{userId}/preferences:
    get:
      summary: Get User Preferences
      description: Retrieve saved preferences for a specific user.
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User preferences retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  categories:
                    type: array
                    items:
                      type: string
                  languages:
                    type: array
                    items:
                      type: string
        '404':
          description: User not found


components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the book
        title:
          type: string
        author:
          type: string
        category:
          type: string
        language:
          type: string
        summary:
          type: string
        publicationYear:
          type: integer
        uploadDetails:
          type: object
          properties:
            uploadedBy:
              type: string
            uploadDate:
              type: string
              format: date-time

security:
  - ApiKeyAuth: []

  
