apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: book-service  # Ensure this matches the built image name
          imagePullPolicy: Never
          ports:
            - containerPort: 8083  # Updated to match EXPOSE in Dockerfile
          env:
            - name: KAFKA_HOST
              value: "kafka"
            - name: KAFKA_PORT
              value: "29092"
            - name: BOOK_SERVICE_DB_HOST
              value: "mysql"
            - name: SCHEMA_REGISTRY_HOST
              value: schema-registry
            - name: API_GATEWAY_HOST
              value: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: NodePort
  selector:
    app: book-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30010