spring:
  application:
    name: OWL_EBook_Searching
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      add-book-topic: add-book-topic
    schema:
      registry:
        url: 'http://127.0.0.1:9091'
  devtools:
    restart:
      enabled: true
      poll-interval: "2s"
      quiet-period: "1s"
    livereload:
      enabled: true
server:
  port: 8084
ontology:
  tbox:
    path: OntologyService/src/main/resources/data/ebook-tbox.owl
  abox:
    path: OntologyService/src/main/resources/data/ebook-abox.owl
  tdb2:
    directory: OntologyService/src/main/resources/data/tdb2
domain: http://qdc.ake
springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html