spring:
  application:
    name: OntologyService
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      add-book-topic: add-book-topic
      add-author-topic: add-author-topic
    schema:
      registry:
        url: http://${SCHEMA_REGISTRY_HOST:127.0.0.1}:9091
server:
  port: 8084
ontology:
  root-prefix: http://www.ebook-searching.org/ontology
  ebook: ${EBOOK_FILE_PATH:OntologyService/src/main/resources/data/ebook.owl}
  tdb2:
    directory: ${DB_DIRECTORY:OntologyService/src/main/resources/data/tdb2}
  domain: http://www.ebook-searching.org/ontology
  ontology-file: ${ONTOLOGY_FILE_PATH:OntologyService/src/main/resources/ontology.owl}
springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
