apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
        - name: storage-service
          image: storage-service  # Ensure this matches the built image name
          imagePullPolicy: Never
          ports:
            - containerPort: 8086  # Updated to match EXPOSE in Dockerfile
          env:
            - name: KAFKA_HOST
              value: "kafka"
            - name: KAFKA_PORT
              value: "29092"
            - name: STORAGE_SERVICE_DB_HOST
              value: "mysql"
            - name: SCHEMA_REGISTRY_HOST
              value: schema-registry
            - name: API_GATEWAY_HOST
              value: api-gateway
            - name: MINIO_ENDPOINT
              value: http://minio:9000
---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  type: NodePort
  selector:
    app: storage-service
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30012